'use strict';
const $=id=>document.getElementById(id);
let data={items:[],sources:[]}, source='all', category='Tümü', summaries={};
let readerTrigger=null;
const categories=['Tümü','Gündem','Dünya','Ekonomi','Teknoloji','Spor'];
const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
function theme(dark){document.body.classList.toggle('dark',dark);$('theme').textContent=dark?'Açık tema':'Koyu tema';$('theme').setAttribute('aria-label',dark?'Açık temaya geç':'Koyu temaya geç');storage.set('haberlerim-theme',dark?'dark':'light')}
theme(storage.get('haberlerim-theme')==='dark');
$('theme').onclick=()=>theme(!document.body.classList.contains('dark'));
$('today').textContent=new Date().toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'});
function safeUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function element(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function dateLabel(value){if(!value)return 'Tarih belirtilmemiş';const d=new Date(value);if(!Number.isFinite(d.getTime()))return 'Tarih belirtilmemiş';return d.toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'})}
function renderSources(){const nav=$('sources');nav.replaceChildren();for(const s of [{id:'all',name:'Bütün kaynaklar'},...data.sources]){const b=element('button',s.id===source?'active':'');b.type='button';b.setAttribute('aria-pressed',String(s.id===source));b.append(element('span',`source-mark ${s.id}`,s.id==='all'?'H':s.id==='t24'?'T24':s.name.slice(0,2).toUpperCase()),element('span','',s.name),element('span','source-count',String(data.items.filter(i=>s.id==='all'||i.source===s.id).length)));b.onclick=()=>{source=s.id;renderSources();render()};nav.append(b)}}
function renderCategories(){const nav=$('categories');nav.replaceChildren();categories.forEach(c=>{const b=element('button',c===category?'active':'',c);b.type='button';b.setAttribute('aria-pressed',String(c===category));b.onclick=()=>{category=c;renderCategories();render()};nav.append(b)})}
function render(){const items=data.items.filter(i=>(source==='all'||i.source===source)&&(category==='Tümü'||i.category===category)).sort((a,b)=>{if($('priority').checked&&source==='all'){const priority=Number(b.source==='t24')-Number(a.source==='t24');if(priority)return priority}return (Date.parse(b.published_at)||0)-(Date.parse(a.published_at)||0)});$('heading').textContent=source==='all'?'Bütün haberler':data.sources.find(s=>s.id===source)?.name||'Haberler';$('count').textContent=`${items.length} haber`;$('sort-label').textContent=$('priority').checked&&source==='all'?'T24 öncelikli · En yeni':'En yeni';const news=$('news');news.replaceChildren();news.setAttribute('aria-busy','false');if(!items.length){news.append(element('div','empty','Bu seçimde henüz haber yok. Başka bir kaynak veya kategori seçebilirsin.'));return}for(const i of items){const url=safeUrl(i.url);if(!url)continue;const card=element('article','card'+(i.source==='t24'?' lead':''));const body=element('div');const meta=element('div','card-meta');meta.append(element('span','source-name',data.sources.find(s=>s.id===i.source)?.name||i.source),element('span','badge',i.category));const time=element('time','',dateLabel(i.published_at));if(i.published_at)time.dateTime=i.published_at;meta.append(time);if(i.via==='google')meta.append(element('span','','Google Haberler üzerinden'));body.append(meta);const title=element('h2');const link=element('button','title-link',i.title);link.type='button';link.onclick=()=>openReader(i,link);title.append(link);body.append(title);const broad=summaries[i.url];const preview=broad?.paragraphs?.[0]||i.summary;if(preview)body.append(element('p','',preview.length>280?preview.slice(0,277)+'…':preview));const read=element('button','read-button',broad?'Geniş özeti oku':i.summary?'Özeti oku':'Okuma ekranı');read.type='button';read.onclick=()=>openReader(i,read);body.append(read);card.append(body);const image=safeUrl(i.image);if(image){const img=element('img');img.src=image;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();card.classList.add('no-image')};card.append(img)}else card.classList.add('no-image');news.append(card)}}
function renderHealth(){const list=$('health-list');list.replaceChildren();for(const s of data.sources){const status=s.status==='ok'?'Güncel':s.status==='homepage'?'Ana sayfa başlıkları':s.status==='fallback'?'Google Haberler akışı':s.status==='cached'?'Önceki haberler gösteriliyor':'Şu anda erişilemiyor';list.append(element('li','',`${s.name}: ${status}`))}}
async function load(){const button=$('refresh');button.disabled=true;button.textContent='Yükleniyor…';try{const r=await fetch(`news.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('Akış okunamadı');const next=await r.json();if(!Array.isArray(next.items)||!Array.isArray(next.sources))throw Error('Geçersiz akış');data=next;try{const sr=await fetch(`summaries.json?t=${Date.now()}`,{cache:'no-store'});if(sr.ok){const sd=await sr.json();summaries=sd.articles&&typeof sd.articles==='object'?sd.articles:{}}}catch{}renderSources();renderCategories();renderHealth();render();const date=new Date(data.updated_at);$('updated').textContent=Number.isFinite(date.getTime())?`Son kontrol: ${dateLabel(data.updated_at)} · 30 dakikada bir güncellenir`:'Henüz haber toplanmadı';const problems=data.sources.filter(s=>!['ok','fallback','homepage'].includes(s.status));const stale=Number.isFinite(date.getTime())&&Date.now()-date.getTime()>2*3600000;$('notice').hidden=!problems.length&&!stale;$('notice').textContent=stale?'Haber akışı bir süredir güncellenmedi. Son alınan haberler gösteriliyor.':`${problems.map(s=>s.name).join(', ')} kaynağına şu anda erişilemiyor. Varsa önceki haberleri gösteriliyor.`}catch(e){$('notice').hidden=false;$('notice').textContent='Haber akışı yüklenemedi. İnternet bağlantını kontrol edip tekrar deneyebilirsin.';$('news').setAttribute('aria-busy','false');if(!data.items.length)$('news').replaceChildren(element('div','empty','Haberler yüklenemedi.'))}finally{button.disabled=false;button.textContent='Akışı yenile'}}
function openReader(item,trigger){
  readerTrigger=trigger;const entry=summaries[item.url];
  const paragraphs=Array.isArray(entry?.paragraphs)?entry.paragraphs.filter(p=>typeof p==='string'&&p.trim()):[];
  const broad=paragraphs.length>0;
  $('reader-source').textContent=data.sources.find(s=>s.id===item.source)?.name||item.source;
  $('reader-title').textContent=item.title;
  $('reader-label').textContent=broad?'GENİŞ ÖZET':item.summary?'KISA ÖZET':'ÖZET HAZIRLANIYOR';
  const published=entry?.published_at||item.published_at;
  $('reader-date').textContent=published?dateLabel(published):'';
  const body=$('reader-body');body.replaceChildren();
  if(broad)for(const paragraph of paragraphs)body.append(element('p','',paragraph));
  else if(item.summary)body.append(element('p','',item.summary));
  else body.append(element('p','','Bu haberin geniş özeti henüz hazırlanmadı. Yeni özetler eklendikçe burada görünecek.'));
  $('reader-note').textContent=broad?'Bu özet, kaynak habere dayanılarak kendi cümlelerimizle hazırlanmıştır. Haberin tamamı değildir.':item.summary?'Bu kısa özet kaynak beslemesinden alınmıştır.':'Başlıktan ayrıntı üretilmez; özet hazırlanması için haber içeriğinin okunması gerekir.';
  const url=safeUrl(item.url);$('reader-original').hidden=!url;if(url)$('reader-original').href=url;
  if(!$('reader').open)$('reader').showModal();document.body.classList.add('reading');$('reader').scrollTop=0;
}
$('reader-close').onclick=()=>$('reader').close();
$('reader').addEventListener('close',()=>{document.body.classList.remove('reading');readerTrigger?.focus()});
$('reader').addEventListener('click',e=>{if(e.target===$('reader')){const r=$('reader').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('reader').close()}});
$('refresh').onclick=load;$('priority').onchange=render;load();
